sudo: required 
language: clojure
jdk:
  - oraclejdk8
install:
  - curl -O https://download.clojure.org/install/linux-install-1.9.0.381.sh
  - chmod +x linux-install-1.9.0.381.sh
  - sudo ./linux-install-1.9.0.381.sh

script:
  - ./runme tests
  - cd example
  - ./runme build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: example/build
  github_token: $GITHUB_TOKEN
  on:
    branch: master
