language: clojure
jdk:
  - oraclejdk8

script:
  - ./runme tests
  - cd example
  - ./runme build

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: example/build
  github_token: $GITHUB_TOKEN
  on:
    branch: master
